env:
  browser: true
  node: true
extends:
  - love
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
ignorePatterns:
  - app.js
  - service.js
  - '*.config.js'
rules:
  '@typescript-eslint/non-nullable-type-assertion-style': off